In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel('data.xlsx')

In [3]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,sales 2018,sales 2019,sales 2020,sales 2021
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,9.0,111,5000,21,27,13495.0,34300.0,18294.0,17200.0,18252.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,9.0,111,5000,21,27,16500.0,12043.0,9444.0,10282.0,10539.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,9.0,154,5000,19,26,16500.0,17075.0,10932.0,7436.0,6297.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,10.0,102,5500,24,30,13950.0,0.0,0.0,0.0,0.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,8.0,115,5500,18,22,17450.0,0.0,0.0,0.0,0.0

In [4]:
df.tail()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,sales 2018,sales 2019,sales 2020,sales 2021
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,9.5,114,5400,23,28,16845.0,0.0,0.0,0.0,0.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,8.7,160,5300,19,25,19045.0,0.0,0.0,0.0,0.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,8.8,134,5500,18,23,21485.0,0.0,0.0,0.0,0.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,23.0,106,4800,26,27,22470.0,0.0,0.0,0.0,0.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,9.5,114,5400,19,25,22625.0,0.0,0.0,0.0,0.0

In [9]:
li = []
for i in range(205):
    li.append(df.iat[i, 26] + df.iat[i, 27] + df.iat[i, 28] + df.iat[i, 29])
df['total_sales'] = li

In [11]:
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,horsepower,peakrpm,citympg,highwaympg,price,sales 2018,sales 2019,sales 2020,sales 2021,total_sales
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,111,5000,21,27,13495.0,34300.0,18294.0,17200.0,18252.0,88046.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,111,5000,21,27,16500.0,12043.0,9444.0,10282.0,10539.0,42308.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,154,5000,19,26,16500.0,17075.0,10932.0,7436.0,6297.0,41740.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,102,5500,24,30,13950.0,0.0,0.0,0.0,0.0,0.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,115,5500,18,22,17450.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,114,5400,23,28,16845.0,0.0,0.0,0.0,0.0,0.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,160,5300,19,25,19045.0,0.0,0.0,0.0,0.0,0.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,134,5500,18,23,21485.0,0.0,0.0,0.0,0.0,0.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,106,4800,26,27,22470.0,0.0,0.0,0.0,0.0,0.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,114,5400,19,25,22625.0,0.0,0.0,0.0,0.0,0.0

In [12]:
df.to_excel('data.xlsx')